name: CI
on:
  push:
    paths:
      - '**/*.ts'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Setup
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Check format
        run: npm run format:check
      - name: Check type
        run: npm run type:check
