name: Transform figma tokens
on:
  push:
    branches:
      - develop
    paths:
      - 'figma/tokens.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Setup
        run: npm install
      - name: Transform figma tokens
        run: npm run transform-figma-tokens
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CREATE_PR }}
          delete-branch: true
          base: 'develop'
          branch: 'update-design-tokens'
          commit-message: 'transform figma tokens'
          title: 'Transform figma tokens'
          body: 'Please review the tokens.json for StyleDictionary.'
